--- #YAML:1.0
name:               googlesearch
version:            1.03
abstract:           command line interface to google search
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::File:          2.04
    Carp:                 1
    Cwd:                  3
    Getopt::Std::Strict:  0
    Google::Search:       0.023
    Smart::Comments:      1
    YAML:                 0.62
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
